// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const windowPane: string;
export const hidden: string;
export const toolbar: string;
export const title: string;
export const close: string;
export const content: string;
export const resizer: string;
