// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tunnel: string;
export const tunnelEdit: string;
export const inputUnderline: string;
export const inputTextWidthTester: string;
export const noselect: string;
