// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const styles: string;
export const header: string;
export const body: string;
export const helpToggler: string;
export const arrow: string;
export const help: string;
export const selector: string;
export const footer: string;
export const error: string;
