// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const account: string;
export const error: string;
export const loginColumns: string;
export const column: string;
