export const safeProperties = [
    'background',
    'background-blend-mode',
    'background-clip',
    'background-color',
    'background-origin',
    'background-position',
    'background-position-x',
    'background-position-y',
    'background-repeat',
    'background-size',
    'border',
    'border-bottom',
    'border-bottom-color',
    'border-bottom-left-radius',
    'border-bottom-right-radius',
    'border-bottom-style',
    'border-bottom-width',
    'border-collapse',
    'border-color',
    'border-left',
    'border-left-color',
    'border-left-style',
    'border-left-width',
    'border-radius',
    'border-radius-bottomleft',
    'border-radius-bottomright',
    'border-radius-topleft',
    'border-radius-topright',
    'border-right',
    'border-right-color',
    'border-right-style',
    'border-right-width',
    'border-spacing',
    'border-style',
    'border-top',
    'border-top-color',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-top-style',
    'border-top-width',
    'border-width',
    'box-shadow',
    'color',
    'font',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'hanging-punctuation',
    'hyphens',
    'justify-content',
    'letter-spacing',
    'line-break',
    'line-height',
    'mix-blend-mode',
    'opacity',
    'outline',
    'outline-color',
    'outline-offset',
    'outline-style',
    'outline-width',
    'overflow',
    'overflow-wrap',
    'overflow-x',
    'overflow-y',
    'padding',
    'padding-bottom',
    'padding-left',
    'padding-right',
    'padding-top',
    'tab-size',
    'text-align',
    'text-align-last',
    'text-decoration',
    'text-decoration-color',
    'text-decoration-line',
    'text-decoration-skip',
    'text-decoration-style',
    'text-indent',
    'text-justify',
    'text-overflow',
    'text-rendering',
    'text-shadow',
    'text-size-adjust',
    'text-space-collapse',
    'text-transform',
    'text-underline-position',
    'text-wrap',
    'transform',
    'transform-origin',
    'transform-style',
    'vertical-align',
    'visibility',
    'white-space',
    'word-break',
    'word-spacing',
];
export const safeFunctions = [
    'attr',
    'calc',
    'circle',
    'counter',
    'counters',
    'cubic-bezier',
    'ellipse',
    'hsl',
    'hsla',
    'lang',
    'line',
    'linear-gradient',
    'matrix',
    'matrix3d',
    'not',
    'nth-child',
    'nth-last-child',
    'nth-last-of-type',
    'nth-of-type',
    'perspective',
    'polygon',
    'polyline',
    'radial-gradient',
    'rect',
    'repeating-linear-gradient',
    'repeating-radial-gradient',
    'rgb',
    'rgba',
    'rotate',
    'rotate3d',
    'rotatex',
    'rotatey',
    'rotatez',
    'scale',
    'scale3d',
    'scalex',
    'scaley',
    'scalez',
    'skewx',
    'skewy',
    'steps',
    'translate',
    'translate3d',
    'translatex',
    'translatey',
    'translatez',
];

export const safeSelectorTags = [
    'blockquote',
    'dd',
    'div',
    'dl',
    'dt',
    'hr',
    'li',
    'ol',
    'p',
    'pre',
    'ul',

    'a',
    'abbr',
    'b',
    'cite',
    'code',
    'data',
    'em',
    'i',
    'mark',
    'q',
    's',
    'samp',
    'small',
    'span',
    'strong',
    'sub',
    'sup',
    'time',
    'var',

    // 'area',
    // 'audio',
    // 'img',
    // 'map',
    // 'track',
    // 'video',

    'caption',
    'col',
    'colgroup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'tr',

    'button',
    'datalist',
    'fieldset',
    'form',
    'input',
    'label',
    'legend',
    'meter',
    'optgroup',
    'option',
    'output',
    'progress',
    'select',
    'textarea',
];

// selectors:
// TODO: check security for id, wildcards (universal), attribute, combinator, pseudo-class
// selectors shouldn't be able to 'jump out' of the room' and affect the toolbar, etc
// always disallow psuedo elements

// rules
// don't allow at-rules?
//    font-face, host, import, keyframes, keyframe, media, namespace, page, supports
