// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const Toolbar: string;
export const toolbar: string;
export const Title: string;
export const title: string;
export const Subtitle: string;
export const subtitle: string;
export const right: string;
export const tool: string;
export const disabled: string;
export const noselect: string;
