// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const StructureWorkshop: string;
export const structureWorkshop: string;
export const seekingPosition: string;
export const hidden: string;
export const structureSelector: string;
export const closeButton: string;
