// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const Mazenet: string;
export const mazenet: string;
export const loading: string;
export const loaded: string;
export const BelowToolbar: string;
export const belowToolbar: string;
